### ISSUE TITLE
#BotStackjs: API Response sends Default and Facebook Messenger Response together

### ISSUE THREAD

**Issue by cama** [cama/botstackjs#14]
Bug : In API.AI if an intent has a response in the "Default" section, and a response in the "Facebook Messenger" section, the default response is sent immediately after the FB response. Switching "Use Default before..." switch does not affect

See issue id 22

https://docs.google.com/spreadsheets/d/1DtsHQ8L4JK4m9pmvgfcSxHJJfB-jHUqxhLz0morp-iY/edit#gid=0

**Comment by webus** [comment]
Done. Added environment variable BOTSTACK_ONLY_FB_RESP. If the variable is present then BotstackJS will process messages from the API.AI, which are addressed only for the platform Facebook (will not be processed messages from the Default tab in the API.AI)

**Comment by cama** [comment]
I like. Thanks!
