### ISSUE TITLE
#Botstackjs: Bug : Postback text in a Card button is being ignored. 

### ISSUE THREAD

**Issue by cama** [cama/botstackjs#21]
Bug : Postback text in a Card button is being ignored. Button label is being used as the postback instead.

Recreate: type "local news". there's a button in the card titled "show me the video". click this button, the the postbakc text for this is "port road drainage video", but when you click the button is acts as if the user typed "show me the video"

**Comment by webus** [comment]
Hmm... Checking now on CCS-Bot. All works correct.

**Comment by webus** [comment]
On chat you see `Show me the video` but BotstackJS send `port road drainage video` to API.AI.

**Comment by webus** [comment]
What is wrong with this behavior ? You want to see "port road drainage video" in chat instead of "Show me the video" ?

**Comment by cama** [comment]
I checked it again and I cannot re-create the issue. The postback seems to be firing the correct intent and returning the video. Closing.
