### ISSUE TITLE
#ACD-Bot: Chat to human does not appear in Slack

### ISSUE THREAD

**Issue by cama** [cama/botstackjs#23]
When a user hits chat to human quick reply it does not surface in Slack. Other quick replies do service in Slack.

**Comment by cama** [comment]
@alex please check out. All messages are going to slack except talk to human.

**Comment by webus** [comment]
Done. Ready to test on `acd-bot-test`

**Comment by cama** [comment]
If it works push to prod

**Comment by webus** [comment]
Done

**Comment by cama** [comment]
thx
