### ISSUE TITLE
Support Custom Payloads in Dialog Flow (Collection of Cards)

### ISSUE THREAD

**Issue by cama** [cama/botstackjs#29]
I need to spoof the listing alerts with Dialogflow for Ylopo.

How much time would it take to update Botstackjs to support a collection of generic templates

https://developers.facebook.com/docs/messenger-platform/send-messages/template/generic

![Screenshot 2018-03-13 14.04.24.png](https://codetreeusercontent.s3.amazonaws.com/uploads/26e428bd-1444-46e8-a452-3955a8dff25b/Screenshot+2018-03-13+14.04.24.png)

https://console.dialogflow.com/api-client/#/agent/ed932e71-cc51-4a31-a647-26d0e5da07f9/editIntent/1b50ef89-91ab-40e6-8577-de4c7173d174/

![Screenshot 2018-03-13 14.01.53.png](https://codetreeusercontent.s3.amazonaws.com/uploads/26e428bd-1444-46e8-a452-3955a8dff25b/Screenshot+2018-03-13+14.01.53.png)

**Comment by webus** [comment]
Done

**Comment by cama** [comment]
thanks!

**Comment by cama** [comment]
This was super important and moved the project along. Thanks for nailing it in a short period.
