### ISSUE TITLE
Add m.me referral capabilities

### ISSUE THREAD

**Issue by cama** [cama/botstackjs#5]
Passing Parameters via M.me Links

In addition to giving bot developers a way to link to their bot, Messenger Platform now also supports the passing an arbitrary parameter via these links.

This can be used for many purposes. It could be used to track different links placed in different channels to see which is most effective. It could also be used to tie a Messenger user to a session or account in an external app. It could even be used to direct the user to specific content or features available within the bot.

e.g.
http://m.me/repostbot?ref=youtube

Provides a report in Facebook Analytics and Dashbot.io on all the users aquired via Youtube

Doco
https://developers.facebook.com/docs/messenger-platform/referral-params

**Comment by webus** [comment]
@cama pls check branch `issue-9`
